### ISSUE TITLE
Feature Request: Cluster Admin creation

### ISSUE THREAD

**Issue by OurFriendIrony** [terraform-redhat/terraform-provider-rhcs#199]
Would it be possible to create a resource for `rosa create admin`?
I believe it is the last manual command execution via the cli I have in my build, and it would be great to fully use the rhcs provider for this instead.

**Comment by arendej** [comment]
Thank you for the feedback.
This is already in our backlog of features and also requires some additions to our API.

**Comment by nirarg** [comment]
Hi @OurFriendIrony ,

Version 1.2.2 already include the option to create cluster with default admin user
In order to use that, please include the [admin credentials](https://registry.terraform.io/providers/terraform-redhat/rhcs/latest/docs/resources/cluster_rosa_classic#nestedatt--admin_credentials) in cluster creation

**Comment by nirarg** [comment]
Closing this issue as it was already solved in verion 1.2.0
