### ISSUE TITLE
Unable to pass private_hosted_zone attributes

### ISSUE THREAD

**Issue by hhh0505** [terraform-redhat/terraform-provider-rhcs#363]
I am currently trying to pass the private_hosted_zone attributes as a schema and i keep getting the following error:

Here is how its defined in my code:

`  private_hosted_zone = {
    id = var.private_hosted_zone_id
    role_arn = var.private_hosted_zone_role_arn
  }`

` Error: Invalid private_hosted_zone attribute assignment
│ 
│   with module.cluster_creation.rhcs_cluster_rosa_classic.rosa_sts_cluster,
│   on modules/cluster_deployment/main.tf line 25, in resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster":
│   25: resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster" {
│ 
│ Invalid configuration. 'private_hosted_zone.id' and
│ 'private_hosted_zone.arn' are required
`

If the values are hardcoded it works, but passing the values as a variable doesn't work

**Comment by nirarg** [comment]
Hi @hhh0505 ,

Thank you for sharing this information

I also faced with this issue, and its seems not related to the provider
We are investigating this issue

Can you share more info, so we can use it during the investigation:
1. Terraform cli version
2. RHCS terraform provider version

**Comment by RelicCornhusk** [comment]
Hi @nirarg ,

I'm working with @hhh0505 on this, here's the info you requested:

1. terraform 1.2.9 x64
2. terraform-redhat/rhcs v1.4.0

**Comment by RelicCornhusk** [comment]
I'll also add that this issue is preventing us from using a resource attribute that is known after apply as the value to `private_hosted_zone.id`. Therefore my interpretation is that this argument does not handle any type of dynamic value as its input. Here is our resource declaration for `rhcs_cluster_rosa_classic`:

```
resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster" {
  name                 = "test-${var.environment}-${var.region_abbreviation}"
  cloud_region         = var.cloud_region
  aws_account_id       = data.aws_caller_identity.current.account_id
  availability_zones   = data.aws_availability_zones.available.names
  replicas             = var.replicas
  autoscaling_enabled  = var.autoscaling_enabled
  min_replicas         = var.min_replicas
  max_replicas         = var.max_replicas
  version              = var.openshift_version
  machine_cidr         = var.machine_cidr
  private              = true
  aws_private_link     = true
  multi_az             = true
  aws_subnet_ids       = var.subnet_ids
  compute_machine_type = var.compute_machine_type
  base_dns_domain      = aws_route53_zone.private.name
  properties = {
    rosa_creator_arn = data.aws_caller_identity.current.arn
  }
  private_hosted_zone = {
    id       = aws_route53_zone.private.zone_id
    role_arn = "arn:aws:iam::<account-id>:role/<role-name>"
  }
  sts                      = local.sts_roles
  wait_for_create_complete = true
}
```

And here is the error:
```
│ Error: Invalid private_hosted_zone attribute assignment
│ 
│   with module.cluster_creation.rhcs_cluster_rosa_classic.rosa_sts_cluster,
│   on modules/cluster_deployment/main.tf line 39, in resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster":
│   39: resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster" {
│ 
│ Invalid configuration. 'private_hosted_zone.id' and
│ 'private_hosted_zone.arn' are required
╵
```

I believe this could be an issue with the [resource validator](https://github.com/terraform-redhat/terraform-provider-rhcs/blob/ee3af2a30c8c34891790d5ed8ad15061592835fc/provider/clusterrosaclassic/validators.go#L47C3-L47C3), more specifically the `function IsStringAttributeEmpty` that seems to only accept a value known during validation, thus not accepting variables or resource attributes known after apply.

This is blocking us in automating from beginning to end a deployment of a ROSA cluster that uses a shared VPC, since that requires reserving a DNS domain with the `rhcs_dns_domain` resource, creating a private hosted zone using that domain and passing its ID to create the cluster.

**Comment by hhh0505** [comment]
@nirarg Is there any update when we could expect a fix for this? This is preventing us from creating a Shared VPC.

**Comment by bardielle** [comment]
@hhh0505 I'm not sure what is the root cause but it's not a specific issue for the RHCS provider... 
The private_hosted_zone attribute is declared as a `SingleNestedAttribute`. 
In order to set and use variables for `private_hosted_zone` it should be declared as a variable from the type object. Please try to update the varibale.tf file with that declaration: 

```
variable "private_hosted_zone" {
  type = object(
    {
      id  = string
      role_arn = string
    }
  )
  default = null
}
```


And then you can pass it in the rosa resource like that:
```
resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster" {
  name           = var.cluster_name
  ......
  private_hosted_zone = var.private_hosted_zone
}
```



If you're passing value into from the CLI you can run it like that:
```
export HOSTED_ZONE_ID=""
export HOSTED_ZONE_ROLE_ARN=""
terraform apply  -var "private_hosted_zone={\"id\"=\"$HOSTED_ZONE_ID\",\"role_arn\"=\"$HOSTED_ZONE_ROLE_ARN\"}"
```


Please update us if it's working for you.

**Comment by hhh0505** [comment]
@bardielle  Thanks for the reply, the only thing is if you create the hosted zone inside the module (which we are) than you reference the resource id to get the hosted zone ID similar to the example that @RelicCornhusk  posted above

`private_hosted_zone = {
    id       = aws_route53_zone.private.zone_id
    role_arn = "arn:aws:iam::<account-id>:role/<role-name>"
  }`

This doesn't work and fails with error above, I suppose we could try to input these values inside of a local to pass it as an object.

**Comment by bardielle** [comment]
I tried debugging it and it seems that the request looks like this:
```
req.ConfigValue =  {"id":<unknown>,"role_arn":"arn:aws:iam::<account-id>:role/<role-name>"}:
```
If I understood it correctly, it means that the output of the `aws_route53_zone` is not known in the plan step, and the validation is done as part of the plan and check if the value is a valid string

I will update it and release it in v1.4.2

**Comment by bardielle** [comment]
@hhh0505 The v1.4.2 would be released on Dec 06

**Comment by bardielle** [comment]
@hhh0505 Sorry for not updating you...  we found one more bug by the QE team so it took us some time to solve it..

**Comment by bardielle** [comment]
Version v1.4.2 was released today.
Please update/ close the issue.

**Comment by hhh0505** [comment]
Issue is fixed, thanks @bardielle
