### ISSUE TITLE
description for parameter `disable_scp_checks` does not look correct and looks to be same as parameter `disable_workload_monitoring`

### ISSUE THREAD

**Issue by vamsinm** [terraform-redhat/terraform-provider-rhcs#383]
description for parameter `disable_scp_checks` does not look correct and looks to be same as parameter `disable_workload_monitoring`

```
disable_scp_checks  (Boolean) Enables you to monitor your own projects in isolation from Red Hat Site Reliability Engineer (SRE) platform metrics.

disable_workload_monitoring (Boolean) Enables you to monitor your own projects in isolation from Red Hat Site Reliability Engineer (SRE) platform metrics.
```

**Comment by bardielle** [comment]
@vamsinm thank you.
I opened a [PR ](https://github.com/terraform-redhat/terraform-provider-rhcs/pull/475)

**Comment by nirarg** [comment]
Thank you @bardielle ,
I see the [PR](https://github.com/terraform-redhat/terraform-provider-rhcs/pull/475) was merged and it was already included in [latest prerelease](https://registry.terraform.io/providers/terraform-redhat/rhcs/latest)
@vamsinm is there any other comment here or can this issue be closed now?

**Comment by bardielle** [comment]
@vamsinm This bug was fixed as part of our last release version 
you can see here that [disable_scp_checks](https://registry.terraform.io/providers/terraform-redhat/rhcs/latest/docs/resources/cluster_rosa_classic#disable_scp_checks)`s description is different than [disable_workload_monitoring](https://registry.terraform.io/providers/terraform-redhat/rhcs/latest/docs/resources/cluster_rosa_classic#disable_workload_monitoring)'s description 

Closing this issue
